export const projects = [
  {
    id: 0,
    title: "dock appointment scheduling system",
    slug: "dock-appointment-scheduling-system",
    shortDescription: "short description",
    longDescription: "longDescription",
    date: "13.12.2025",
    technologies: ["nextjs", "tailwind css", "i18next", "next-auth"],
  },
  {
    id: 1,
    title: "galéria u anjela",
    slug: "galeria-u-anjela",
    shortDescription: "short description",
    longDescription: "longDescription",
    date: "13.12.2025",
    technologies: [
      "nextjs",
      "tailwind css",
      "i18next",
      "payload",
      "and design",
      "prisma",
      "postgresql",
    ],
  },
  {
    id: 2,
    title: "portfolio",
    slug: "portfolio",
    shortDescription: "short description",
    longDescription: "longDescription",
    date: "13.12.2025",
    technologies: [
      "nextjs",
      "chakra",
      "i18next",
      "prisma",
      "postgresql",
      "oauth",
    ],
  },
  {
    id: 3,
    title: "dock appointment scheduling system",
    slug: "dock-appointment-scheduling-system-2",
    shortDescription: "short description",
    longDescription: "longDescription",
    date: "13.12.2025",
    technologies: ["nextjs", "tailwind css", "i18next", "next-auth"],
  },
  {
    id: 4,
    title: "galéria u anjela",
    slug: "galeria-u-anjela-2",
    shortDescription: "short description",
    longDescription: "longDescription",
    date: "13.12.2025",
    technologies: [
      "nextjs",
      "tailwind css",
      "i18next",
      "payload",
      "and design",
      "prisma",
      "postgresql",
    ],
  },
  {
    id: 5,
    title: "portfolio",
    slug: "portfolio-2",
    shortDescription: "short description",
    longDescription: "longDescription",
    date: "13.12.2025",
    technologies: [
      "nextjs",
      "chakra",
      "i18next",
      "prisma",
      "postgresql",
      "oauth",
    ],
  },
];
